CREATE TABLE AMTDB.CUSTOMER_DETAILS
(
  CUSTOMER_ID int(6) ,
  FIRST_NAME varchar(50) not null,
  LAST_NAME varchar(50),
  MIDDLE_NAME varchar(50),
  MOBILE_NUMBER int(12),
  LAND_LINE_NUMBER int(12),
  DOB date,
  GENDER varchar(8),
  IDENTITY_CARD_TYPE  VARCHAR(50),
  IDENTITY_CARD_NUMBER  VARCHAR(50),
  primary key(CUSTOMER_ID)
);

CREATE TABLE AMTDB.ADDRESS(
  CUSTOMER_ID INT(6) NOT NULL,
  ADDR_1  VARCHAR(255),
  ADDR_2  VARCHAR(255),
  EMAIL   VARCHAR(50),
  DISTRICT  VARCHAR(50),
  CITY      VARCHAR(50),
  POSTAL_CODE INTEGER(6),
  PRIMARY_CONTACT_NUMBER  INTEGER(11),
  SECONDARY_CONTACT_NUMBER  INTEGER(11),
  CREATE_DT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE TIMESTAMP,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMTDB.CUSTOMER_DETAILS(CUSTOMER_ID)
);

CREATE TABLE AMTDB.AGENT_DETAILS(
  AGENT_ID  INT(6),
  FIRST_NAME  VARCHAR(50),
  LAST_NAME   VARCHAR(50),
  MIDDLE_NAME VARCHAR(50),
  EMAIL       VARCHAR(150),
  MOBILE_NUMBER int(12),
  DOB         DATE,
  IDENTITY_CARD_TYPE  VARCHAR(50),
  IDENTITY_CARD_NUMBER  VARCHAR(50),
  CREATE_DT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE TIMESTAMP,
  PRIMARY KEY(AGENT_ID)
);

CREATE TABLE AMTDB.SHOP(
  SHOP_ID   INT(10),
  LICENCE_ID    VARCHAR(50),
  OWNER_FIRST_NAME  VARCHAR(50),
  MOBILE_NUMBER int(12),
  ADDR_1  VARCHAR(255),
  OWNER_LAST_NAME   VARCHAR(50),
  OWNER_MIDDLE_NAME VARCHAR(50),
  IDENTITY_CARD_TYPE  VARCHAR(50) NOT NULL,
  IDENTITY_CARD_NUMBER  VARCHAR(50) NOT NULL,
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP,
  PRIMARY KEY (SHOP_ID)
);

CREATE TABLE AMTDB.INVENTORY_ITEM(
  ITEM_NUMBER   INT(10),
  ITEM_NAME     VARCHAR(50),
  ITEM_TYPE     VARCHAR(50),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP,
  PRIMARY KEY (ITEM_NUMBER)
);

CREATE TABLE AMTDB.ITEM_PRICE(
  ITEM_NUMBER   INT(10),
  MRP           DOUBLE(10,2),
  SP            DOUBLE(10,2),
  DISCOUNT_PERCENT  INT(2),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.ORDER_DETAILS(
  ORDER_NUM   VARCHAR(50),
  QTY         INT(10),
  TOTAL_AMT   DOUBLE(10,2),
  AMT_PAID DOUBLE(10,2),
  AMT_DUE  DOUBLE(10,2),
  ADVANCE_AMT DOUBLE(10,2),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.ORDER_HISTORY(
  ORDER_NUM   VARCHAR(50),
  TOTAL_AMT   INT(10),
  NOTES       BLOB,
  ORDER_PLACED_DT   DATETIME,
  ORDER_DELIVERED_DT  DATETIME,
  ORDER_DELIVERED_BY  VARCHAR(50),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.ORDER_TRACKING(
  ORDER_NUM   VARCHAR(50) NOT NULL,
  TRACKING_ID VARCHAR(50) NOT NULL,
  ORDER_STAGE VARCHAR(40) NOT NULL,
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.TRACKING_DESC(
  TRACKING_ID VARCHAR(50) NOT NULL,
  ITEM_CURRENT_LOCATION   VARCHAR(50)
);

CREATE TABLE AMTDB.SHIPPING(
  SHIPPING_ID   VARCHAR(25),
  SHIPMENT_METHOD VARCHAR(25),
  SHIPPING_CHARGE DOUBLE(10,2),
  SHIPPING_DATE   DATETIME,
  SHIPPING_COUNTRY  VARCHAR(40),
  SHIPPING_STATE    VARCHAR(40),
  SHIPPING_CITY     VARCHAR(40),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP,
  PRIMARY KEY (SHIPPING_ID)
);

CREATE TABLE AMTDB.PAYMENT(
  PAYMENT_NUM   VARCHAR(40),
  AMT_PAID DOUBLE(10,2),
  PAYMENT_MODE  VARCHAR(40),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.INVOICE(
  INVOICE_NUM   VARCHAR(40),
  CREATE_DT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE   TIMESTAMP
);

CREATE TABLE AMTDB.DELIVERY_DETAILS(
  DEL_DT    DATETIME,
  DEL_ITEM  VARCHAR(40),
  DEL_BY    VARCHAR(40),
  DEL_TO    VARCHAR(40),
  DEL_LOCATION  VARCHAR(255),
  ITEM_MADE_BY  VARCHAR(100)
);

